# Generated by Django 6.0.7 on 2026-08-05 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(max_length=20, unique=True)),
                ('profile_type', models.CharField(choices=[('BRIDE', 'Bride'), ('GROOM', 'Groom')], max_length=10)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('marital_status', models.CharField(choices=[('NEVER_MARRIED', 'Never Married'), ('DIVORCED', 'Divorced'), ('WIDOW', 'Widow'), ('WIDOWER', 'Widower')], max_length=20)),
                ('height', models.DecimalField(decimal_places=1, max_digits=4)),
                ('weight', models.PositiveIntegerField()),
                ('education', models.CharField(max_length=150)),
                ('occupation', models.CharField(max_length=150)),
                ('annual_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('about_me', models.TextField()),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profiles/photos/')),
                ('is_profile_completed', models.BooleanField(default=False)),
                ('profile_status', models.CharField(choices=[('NEW', 'New'), ('VERIFIED', 'Verified'), ('MATCHED', 'Matched'), ('MARRIED', 'Married'), ('BLOCKED', 'Blocked')], default='NEW', max_length=20)),
                ('is_photo_visible', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('denomination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='common.denomination')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
