# Generated by Django 6.0.7 on 2026-08-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(choices=[('UNMARRIED', 'Unmarried'), ('DIVORCED', 'Divorced'), ('WIDOW', 'Widow'), ('WIDOWER', 'Widower')], max_length=20),
        ),
    ]
