# Generated by Django 6.0.7 on 2026-08-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_marital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_status',
            field=models.CharField(choices=[('NEW', 'New'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('MATCHED', 'Matched'), ('MARRIED', 'Married'), ('BLOCKED', 'Blocked')], default='NEW', max_length=20),
        ),
    ]
