# Generated by Django 6.0.7 on 2026-08-10 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0003_alter_profile_profile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('father_occupation', models.CharField(blank=True, max_length=150)),
                ('mother_occupation', models.CharField(blank=True, max_length=150)),
                ('brothers', models.PositiveIntegerField(default=0)),
                ('sisters', models.PositiveIntegerField(default=0)),
                ('family_type', models.CharField(choices=[('NUCLEAR', 'Nuclear'), ('JOINT', 'Joint')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family', to='profiles.profile')),
            ],
        ),
    ]
