# Generated by Django 6.0.7 on 2026-08-10 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0003_alter_profile_profile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaar', models.FileField(blank=True, null=True, upload_to='profiles/documents/aadhaar/')),
                ('aadhaar_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('baptism_certificate', models.FileField(blank=True, null=True, upload_to='profiles/documents/baptism/')),
                ('baptism_certificate_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('education_certificate', models.FileField(blank=True, null=True, upload_to='profiles/documents/education/')),
                ('education_certificate_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('income_certificate', models.FileField(blank=True, null=True, upload_to='profiles/documents/income/')),
                ('income_certificate_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('other_document', models.FileField(blank=True, null=True, upload_to='profiles/documents/other/')),
                ('other_document_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='profiles.profile')),
            ],
        ),
    ]
